### ISSUE TITLE
failed to load command: ./dependabot.rb

### ISSUE THREAD

**Issue by GeertvanHorrik** [nils-org/dependabot-cake-action#4]
Since some time, the jobs are failing on some packages:

https://github.com/GeertvanHorrik/RepositoryTemplate/runs/2397497303?check_suite_focus=true#step:3:24

Any idea what could be causing this?

**Comment by nils-a** [comment]
Not really, no. I will have look at it.

**Comment by nils-a** [comment]
@GeertvanHorrik the error seems to be upstream, at https://github.com/pharos/dependabot-core/tree/add-support-for-cake (which is the "real" implementation of "Cake for dependabot"). 

However, that code is six months old and seemingly never updated. I'll try to get my head around producing a workable version to see what the error might be.

**Comment by nils-a** [comment]
Ok, I "found" the error.
The error is, that no `*.cake` files are found in that repository. Seemingly, only `*.cake` files in the root folder are taken into consideration and if no files are found dependabot errors out.

**Comment by GeertvanHorrik** [comment]
Wow, that's interesting. It has used great for me for quite a while now. But you are right, this is a repository template so only contains .cake files in subfolders.

**Comment by nils-a** [comment]
I'll see whether I can add configuration options to the action to make the folder configurable.

In the meantime: Have you had a look at [renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate)? Renovate supports Cake out-of-the-box and does recursive search by default... I've written about it in the [cakebuild.net blog](https://cakebuild.net/blog/2021/04/cake-support-in-renovate).

**Comment by nils-a** [comment]
@GeertvanHorrik forget everything I said (well, except that part about renovate) I see I did make the directory configurable, and that you in fact did set it correctly. However, I still see an error. Will investigate further.

**Comment by nils-a** [comment]
Found it - for real this time. 
Not sure if my Ruby is good enough to fix it, though. 

The problem is, as follows: You referenced `Cake.FileHelpers` twice
- in `tasks.cake` in version 3.3.0
- in `templates-tasks.cake` in version 3.0.0

somehow the cake module in dependabot squashes this into one update procedure `Cake.FileHelpers` from version 3.3.0 to 4.0.1.
When it reaches `templates-tasks.cake` it tries to replace `version=3.3.0` with `version=4.0.1` (which fails since 3.3.0 is not referenced there.)

So.. As a workaround I would suggest you update `templates-tasks.cake` to reference `Cake.FileHelpers` in version 3.3.0 (so both are the same again) and let dependabot do it's magic.

**Comment by GeertvanHorrik** [comment]
Thank you. Interesting it goes wrong there (while it seems to have worked fine for a while). I will definitely remove this, thanks a lot for your research on this.

**Comment by nils-a** [comment]
It gave the excuse to start digging into the dependabot and ruby stuff, so actually: Thank you 😄 

I'm tracking the error in #5 and will see what to do about it.

**Comment by GeertvanHorrik** [comment]
Just wanted to provide feedback, it's all working again after removing the duplicate addin definition:

![image](https://user-images.githubusercontent.com/1246444/115838497-07173b00-a41a-11eb-8bbd-0c0f986b8057.png)

Thanks again!
